- tasks:
  - type: opspace::CartPosTask
    name: eepos_goal
    end_effector: 6
    control_point: [ 0.0, 0.0, 0.0 ]
    kp: [ 200.0 ]
    kd: [ 10.0 ]
    maxvel: [ 2.0 ]
  - type: opspace::SelectedJointPostureTask
    name: posture
    kp: 40.0
    kd: 5.0
    selection: [ 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0 ]

- skills:
  - type: uta_opspace::DynamicAccuracyTest
    name: dynamic_accuracy
    center_position:  [ 0.40, -0.25, -0.10 ]
    radius: 0.1
    omega: 2
    slots:
      goal_eepos: eepos_goal
      posture: posture
      