- tasks:
  - type: opspace::CartPosTrjTask
    name: eepos
    end_effector_id: 6
    sigma_threshold: 0.005
    control_point: [ 0.0, 0.0, 0.0 ]
    dt_seconds: 0.0025
    kp: [ 200.0 ]
    kd: [ 10.0 ]
    maxvel: [ 0.55 ]
    maxacc: [ 2.00 ]
  - type: opspace::JPosTrjTask
    name: posture
    sigma_threshold: 0.0001
    dt_seconds: 0.0025
    kp: [ 100.0 ]
    kd: [  10.0 ]
    #kp: [ 0.0 ]
    #kd: [ 0.0 ]
    maxvel: [ 2.0 ]
    maxacc: [ 10.0 ]
  - type: opspace::JPosTrjTask
    name: joint
    sigma_threshold: 0.0001
    dt_seconds: 0.0025
    kp: [ 150.0 ]
    kd: [  10.0 ]
    #kp: [ 0.0 ]
    #kd: [ 0.0 ]
    maxvel: [ 1.0 ]
    maxacc: [ 3.0 ]
  - type: opspace::OrientationTask
    name: eeori
    end_effector_id: 6
    kp: 300.0
    kd: 10.0
    maxvel: 6.0
    
- skills:
  - type: uta_opspace::GestureSkill
    name: gesture
    eepos: [ 0.25, -0.30, 0.08,
	     0.25, -0.10, 0.08,
	     0.25, -0.35, 0.08,
	     0.25, -0.10, 0.08,
	     0.30, -0.30,-0.25,
	     0.05, -0.55,-0.25,
	     0.05, -0.50, 0.00,
	     0.16, -0.38, 0.15,
	     0.30, -0.20, 0.00,
	     0.25, -0.40,-0.10,
	     0.30, -0.25,-0.10,
	     0.30, -0.25, 0.00,
	     0.30, -0.35, 0.00,
	     0.30, -0.35,-0.10,
	     0.30, -0.25,-0.10,
	     0.30, -0.35, 0.00,
	     0.20, -0.10, 0.25,
	     0.35, -0.20, 0.17,
	     0.20, -0.20,-0.50 ]
    eeori_x: [ 0, -0.866,  -0.5,
	       0, -0.866,   0.5,
	       0, -0.866,  -0.5,
	       0, -0.866,   0.5,
	       0,     -1,     0,
	      -1,      0,     0,
	      -1,      0,     0,
	       0,     -1,     0,
	       0,     -1,     0,
	   -0.65,  -0.75,     0,
	       0,     -1,     0,
	       0,     -1,     0,
	       0,     -1,     0,
	       0,     -1,     0,
	       0,     -1,     0,
	       0,     -1,     0,
	       1,      0,     0,
	       1,      0,     0,
	       0,     -1,     0 ]
    eeori_y: [ 0,  0.5, -0.866,
	       0, -0.5, -0.866,
	       0,  0.5, -0.866,
	       0, -0.5, -0.866,
	      -1,    0,      0,
	       0,    1,      0,
	       0,    0,     -1,
	       0,    0,     -1,
	       0,    0,     -1,
	       0,    0,     -1,
	       0,    0,     -1,
	       0,    0,     -1,
	       0,    0,     -1,
	       0,    0,     -1,
	       0,    0,     -1,
	       0,    0,     -1,
	       0,-0.866, -0.5,
	       0, -0.8,   -0.6,
	   -0.63,    0,   0.77 ]
    eeori_z: [ 1, 0, 0,
	       1, 0, 0,
	       1, 0, 0,
	       1, 0, 0,
	       0, 0, -1,
	       0, 0, -1,
	       0,-1,  0,
	       1, 0,  0,
	       1, 0,  0,
	     0.75, -0.65, 0,
	       1, 0, 0,
	       1, 0, 0,
	       1, 0, 0,
	       1, 0, 0,
	       1, 0, 0,
	       1, 0, 0,
	       0, 0.5, -0.866,
	       0, 0.6, -0.8,
	   -0.77,   0, -0.63 ]
    posture: [ 0.80, 0.65, 0.0, 1.8, 0.0, 0.0, 0.0,	
	       0.80, 0.65, 0.0, 1.8, 0.0, 0.0, 0.0,
	       0.80, 0.65, 0.0, 1.8, 0.0, 0.0, 0.0,
	       0.80, 0.65, 0.0, 1.8, 0.0, 0.0, 0.0,
	       0.00, 0.25, 0.0, 1.57, 0.0, 0.0, 0.0,
	       0.00, 0.25, 1.57, 1.57, 0.0, 0.0, 0.0,
	       0.00, 0.45, 1.57, 2.00, 0.0, 0.5, 0.0,
	       0.90, 0.30, 0.60, 2.20, 0.5,-0.25,-0.20,
 	       0.9235, 0.5, -0.4046, 1.4264, 1.3167, 1.0327, -1.0484,
	       0.30, 0.10, 0.80, 1.8, 0.0, 0.5, 0.0,
	       0.36, 0.00, 0.00, 1.73, 0.00, 1.00, 0.00,
	       0.36, 0.00, 0.00, 1.73, 0.00, 1.00, 0.00,
	       0.36, 0.00, 0.00, 1.73, 0.00, 1.00, 0.00,
	       0.36, 0.00, 0.00, 1.73, 0.00, 1.00, 0.00,
	       0.36, 0.00, 0.00, 1.73, 0.00, 1.00, 0.00,
	       0.36, 0.72, 0.00, 1.73, 0.00, 1.00, 0.00,
	       1.49, 0.10, -0.5, 1.95, 1.8, -0.5, 0.35,
	       1.29, 0.30, -0.4, 1.59, 1.46, -0.5, -0.4,
	       0.15, 0.0,   0.0,  0.5, 0.0,   0.0,  0.0 ]
    threshold: 0.08
    joint_positions: [1.3249, 0.4010, -0.4218, 2.2643, 1.8517, -0.3638, 0.3338 ]
    hold_count: [ 0, 0, 0, 300, 500, 500, 300, 100, 300, 500, 300, 300, 300, 300, 500, 300,  500, 300, 0]
    vel_threshold: 0.03

    slots:
      eepos: eepos
      eeori: eeori
      posture: posture
      joint: joint
