- tasks:
  - type: opspace::OrientationTask
    name: eeori
    end_effector_id: 6
    sigma_threshold: 0.0001
    kp: 600.0
    kd: 10.0
    maxvel: 12.0
  - type: opspace::CartPosTrjTask
    name: eepos
    end_effector_id: 6
    sigma_threshold: 0.0001
    control_point: [ 0.0, 0.0, 0.0 ]
    dt_seconds: 0.002
    kp: [ 0.0 ]
    kd: [ 3.0 ]
    maxvel: [ 0.8 ]
    maxacc: [ 0.4 ]
  - type: opspace::JPosTask
    name: posture
    sigma_threshold: 0.0001
    kp: [ 0.0 ]
    kd: [ 3.0 ]
    maxvel: [ 10.0 ]

- behaviors:
  - type: opspace::GenericBehavior
    name: exp
    slots:
    - task: eeori
    - task: eepos
    - task: posture
