- tasks:
  - type: opspace::TestPureJointTask
    name: jpos
    kp: [ 200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0 ]
    kd: [   5.0,   5.0,   5.0,   5.0,   5.0,   5.0,   5.0 ]
    selection: [ 0, 0, 1, 0, 0, 0, 0]
    amplitude: 1.0
    omega: 2
    goalpos: [ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

- skills:
  - type: opspace::GenericSkill
    name: generic
    slots:
      task: jpos
