- tasks:
  - type: opspace::CartPosTask
    name: eepos_goal
    end_effector: 6
    control_point: [ 0.0, 0.0, 0.0 ]
    kp: [ 300.0 ]
    kd: [ 5.0 ]
    maxvel: [ 0.8 ]
  - type: opspace::CartPosTask
    name: eepos_away
    end_effector: 6
    control_point: [ 0.0, 0.0, 0.0 ]
    kp: [ 300.0 ]
    kd: [  5.0 ]
    maxvel: [ 0.8 ]
  - type: opspace::SelectedJointPostureTask
    name: posture
    kp: 40.0
    kd:  5.0
    selection: [ 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0 ] 

- skills:
  - type: uta_opspace::StaticAccuracyTest
    name: static_accuracy
    hold_time: 5000
    goal_position:  [ 0.40, -0.33,  0.00 ]
    away_position:  [ 0.30, -0.33, -0.20 ]
    slots:
      posture: posture
      goal_eepos: eepos_goal
      away_eepos: eepos_away
      