- tasks:
  - type: opspace::TestVarGainCartPosTask
    name: task
    end_effector: 6
    kp: [ 100.0, 0.0, 100.0 ]
    kd: [  10.0,  10.0, 10.0 ]
    control_point: [ 0, 0, 0]
    goalpos: [ 0.30, -0.25, 0.0]
  - type: opspace::JPosTrjTask
    name: posture
    sigma_threshold: 0.0001
    dt_seconds: 0.0025
    kp: [ 0.0 ]
    kd: [ 0.0 ]
    maxvel: [ 1.0 ]
    maxacc: [ 3.0 ] 
  - type: opspace::SelectedJointPostureTask
    name: task2
    kp: 80.0
    kd:  5.0
    selection: [ 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0 ] 

- skills:
  - type: opspace::ThreeTaskSkill
    name: threetask
    slots:
      task1: task
      task2: task2
      task3: posture
