- tasks:
  - type: opspace::CartPosTrjTask
    name: eepos
    end_effector_id: 6
    sigma_threshold: 0.005
    control_point: [ 0.0, 0.0, 0.0 ]
    dt_seconds: 0.0025
    kp: [ 100.0 ]
    kd: [ 25.0 ]
    maxvel: [ 0.5 ]
    maxacc: [ 1.0 ]
  - type: opspace::SelectedJointPostureTask
    name: posture
    kp: 40.0
    kd:  5.0
    selection: [ 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0 ] 

- skills:
  - type: uta_opspace::TrajAccuracyTest
    name: traj_test
    eepos_goal: [ 0.40, -0.33, 0.00 ]
    eepos_origin: [ 0.30, -0.33, -0.20 ]
    hold_time: 5000
    slots:
      eepos: eepos
      posture: posture