- tasks:
  - type: opspace::CartPosTask
    name: eepos
    sigma_threshold: 0.00001
    end_effector: l_forearm_roll_link
    control_point: [ 0.0, -0.15, 0.0 ]
    kp: [ 150.0 ]
    kd: [  20.0 ]
    maxvel: [ 0.5 ]
  - type: opspace::JPosTask
    name: posture
    sigma_threshold: 0.0001
    kp: [ 100.0 ]
    kd: [  20.0 ]
    maxvel: [ 1.6 ]
- behaviors:
  - type: opspace::TaskPostureBehavior
    name: task_posture
    default:
      eepos: eepos
      posture: posture
