wbc_pr2_ctrl:
  tao_root_name: torso_lift_link
  active_links:
   - l_shoulder_pan_link
   - l_shoulder_lift_link
   - l_upper_arm_roll_link
   - l_elbow_flex_link
   - l_forearm_roll_link
   - l_wrist_flex_link
   - l_wrist_roll_link
   - r_shoulder_pan_link
   - r_shoulder_lift_link
   - r_upper_arm_roll_link
   - r_elbow_flex_link
   - r_forearm_roll_link
   - r_wrist_flex_link
   - r_wrist_roll_link
  gravity_compensated_links:
   - l_shoulder_pan_link
   - l_shoulder_lift_link
   - l_upper_arm_roll_link
   - l_elbow_flex_link
   - l_forearm_roll_link
   - l_wrist_flex_link
   - l_wrist_roll_link
   - r_shoulder_pan_link
   - r_shoulder_lift_link
   - r_upper_arm_roll_link
   - r_elbow_flex_link
   - r_forearm_roll_link
   - r_wrist_flex_link
   - r_wrist_roll_link
  gains:
   l_shoulder_pan_joint:   { kp: 800, kd: 10 }
   l_shoulder_lift_joint:  { kp: 800, kd: 10 }
   l_upper_arm_roll_joint: { kp: 200, kd:  3 }
   l_elbow_flex_joint:     { kp: 100, kd:  3 }
   l_forearm_roll_joint:   { kp: 500, kd:  6 }
   l_wrist_flex_joint:     { kp: 400, kd:  4 }
   l_wrist_roll_joint:     { kp: 400, kd:  4 }
   r_shoulder_pan_joint:   { kp: 800, kd: 10 }
   r_shoulder_lift_joint:  { kp: 800, kd: 10 }
   r_upper_arm_roll_joint: { kp: 200, kd:  3 }
   r_elbow_flex_joint:     { kp: 100, kd:  3 }
   r_forearm_roll_joint:   { kp: 500, kd:  6 }
   r_wrist_flex_joint:     { kp: 400, kd:  4 }
   r_wrist_roll_joint:     { kp: 400, kd:  4 }
